services:
  db:
    image: postgres:latest
    container_name: recipe-db
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "127.0.0.1:5432:5432"


  app:
    build: .
    container_name: recipe-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe
    ports:
      - "127.0.0.1:8080:8080"

