apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipe_ue5.fullname" . }}
  labels:
    {{- include "recipe_ue5.labels" . | nindent 4 }}
    {{- with .Values.podAnnotations }}
    annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name | quote }}
  selector:
    {{- include "recipe_ue5.selectorLabels" . | nindent 4 }}
    io.compose.service: {{ .Values.selector.service }}