name: ci

on:
  push:
    branches:
      - "main"
      
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  LOCAL_TAG: recipe-app:ci

jobs:
  lint:
    name: Lint Go and Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: src
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  
  build_check:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.LOCAL_TAG }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.LOCAL_TAG }}
          format: table
          ignore-unfixed: false
          severity: CRITICAL,HIGH
          exit-code: 1
          
      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: Run Python Tests
        run: python3 test.py

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64